
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module MyComputer(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
//	input 		          		CLOCK2_50,
//	input 		          		CLOCK3_50,
//	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [7:0] Dout;
	wire [7:0] IP;
	wire Dval;
	wire Reset;

//=======================================================
//  Structural coding
//=======================================================

CPU cpu(
	
	.Clock(CLOCK_50), 
	.GPO(LEDR[5:0]), 
	.Debug(LEDR[9:6]), 
	.Din(SW[7:0]), 
	.Turbo(SW[8]), 
	.Sample(~KEY[3]), 
	.Btns(~KEY[2:0]), 
	.Reset(Reset), 
	.Dout(Dout),
	.Dval(Dval), 
	.IP(IP)
);

	DeBounce Rst(CLOCK_50, SW[9], Reset);

	Disp2cNum Disp_Dout(Dout, Dval, HEX0, HEX1, HEX2, HEX3);

	DispHex Disp_IP(IP, HEX4, HEX5);

endmodule
